//
//  MainPresenter.swift
//  WalkQuest
//
//  Created by David on 1/3/17.
//  Copyright (c) 2017 damarte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MainPresenterInput
{
  func presentSomething(response: Main.Something.Response)
}

protocol MainPresenterOutput: class
{
  func displaySomething(viewModel: Main.Something.ViewModel)
}

class MainPresenter: MainPresenterInput
{
  weak var output: MainPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Main.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Main.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
